### ISSUE TITLE
Remove "It is not possible to run any games" in README

### ISSUE THREAD

**Issue by ArbestRiAgain** [RPCSX/rpcsx#28]
RPCSX can already boot We Are Doomed (commercial game)
![image](https://github.com/RPCSX/rpcsx/assets/132712354/1674c94e-71e0-4e61-84d1-27315fec29b4)
And the video for this is on https://www.youtube.com/watch?v=k2dc9gUOq0c. So that's why "It is NOT possible to run any games yet" in README should be removed and add in a notice in README saying that the emulator can currently only run 1 commercial game.

**Comment by RyzenDew** [comment]
And when it runs more do we always update the count ? Nah thats silly and we are doomed runs at 1fps every 5-6 seconds.

**Comment by ArbestRiAgain** [comment]
According to this video now (https://youtu.be/dS9J-l0cFqk) RPCSX runs We Are Doomed faster, and no, we shouldn't always update the count, as that could be a waste of time.

**Comment by Brutal-sam** [comment]
and Sonic Mania is booting and running at 45 fps https://youtu.be/2VLXIQjdINs I think it's time to start making a compatability repo

**Comment by DrLegitamate** [comment]
I'm assuming for the sake of an easy life for the devs saying that RPCSX can "run" a game officially would be better left for the moment a game can actually be interacted with and give reasonable feedback (i.e. a keyboard press does something and the graphics are discernible enough to see the input works) as saying a game runs and then the average joe tries to play it and met with a green flickering screen with no way of actually selecting play in a start screen, then running to discord to complain they were lied to only causes problems instead of solves

**Comment by Brutal-sam** [comment]
people can refer to this https://docs.google.com/spreadsheets/d/1f02oterEI_mcX680ZYzxMSM2Yg4C2FICqooKZ8NVqF0/edit?usp=sharing till the emu is booting enough games and the dev makes a compatibility repo
