### ISSUE TITLE
Related website

### ISSUE THREAD

**Issue by dhalucario** [RPCSX/rpcsx#65]
Hey, I don't see https://rpcsx.com/ in the README of this repo. But when searching for rpcsx it's the first site to pop up on Google. For clarification, is the website related to this project?

**Comment by yodaxtah** [comment]
Well, [https://rpcsx.org/](https://rpcsx.org/) isn't probably not yours either. It seems similar to RPCS3's website and even accidentally mentions RPCS3 instead of RPCSX under **Contribute to RPCSX on Github**
![image](https://github.com/RPCSX/rpcsx/assets/159531413/7fe6e928-f47c-4dcf-b734-a7b7e1a1a726)

I just distrust all the sites that tell me they're open source and not provide me a url to the project. This particular site has surprisingly the following urls in download buttons (but lacks any other references to this project):
- https://github.com/RPCSX/rpcsx/releases/download/rpcsx-v20231111/rpcsx-v20231111.zip as "Download"
- https://github.com/RPCSX/rpcsx/releases/download/rpcsx-v20231111/rpcsx-v20231111.zip as "Download APK"
Yes, the same url, twice. That's how I found this project (previewing the download url), as the scam site appeared before yours. They can change it in the future to point to something malicious though.

For anyone wondering, these sites are suspicious as well:
- https://pcsx4emulator.com/announcing-pcsx4/ no github, blogs are barely explaining anything and point to the download page
- https://rpcs4.com/compatibility they have a very convincing commit message page, yet they are not linking to any repository

**Comment by DHrpcs3** [comment]
@yodaxtah Thank you for investigation. Yeah, they all are scam sites. Domain of rpcsx.com was registered in 10+ years ago that is why it going before our site in search.
(possible dangerous links in your message are not clickable now)


**https://rpcsx.github.io/ (old link https://rpcsx.github.io/rpcsx-site) is only site that has relations with this project**
